# Generated by Django 4.2.7 on 2025-07-12 12:49

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le CIN doit être au format: A123456 ou AB123456', regex='^[A-Z]{1,2}\\d{6}$')], verbose_name='CIN du chauffeur')),
                ('plaque_camion', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='La plaque doit être au format: 123-A-456 ou 1234-ABC-12', regex='^\\d{3,4}-[A-Z]{1,3}-\\d{1,4}$')], verbose_name='Plaque du camion')),
                ('numero_conteneur', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Le numéro de conteneur doit être au format: ABCD1234567', regex='^[A-Z]{4}\\d{7}$')], verbose_name='Numéro de conteneur')),
                ('sens_trafic', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Sens du trafic')),
                ('type_conteneur', models.CharField(choices=[('plein', 'Plein'), ('vide', 'Vide')], max_length=5, verbose_name='Type de conteneur')),
                ('operation', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=10, verbose_name="Type d'opération")),
                ('date_rdv', models.DateField(verbose_name='Date du rendez-vous')),
                ('heure_rdv', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('code_unique', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_creation'],
            },
        ),
    ]
