# Generated by Django 4.2.7 on 2025-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='cin',
            field=models.CharField(max_length=20, verbose_name='CIN du chauffeur'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='numero_conteneur',
            field=models.CharField(max_length=11, verbose_name='Numéro de conteneur'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='operation',
            field=models.CharField(choices=[('import', 'Import'), ('export', 'Export')], default='import', max_length=10, verbose_name="Type d'opération"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='plaque_camion',
            field=models.CharField(max_length=20, verbose_name='Plaque du camion'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='sens_trafic',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], default='entree', max_length=10, verbose_name='Sens du trafic'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='type_conteneur',
            field=models.CharField(choices=[('plein', 'Plein'), ('vide', 'Vide')], default='vide', max_length=5, verbose_name='Type de conteneur'),
        ),
    ]
