# Generated by Django 4.2.7 on 2025-07-12 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0002_remove_rendezvous_qr_code_alter_rendezvous_cin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='cin',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le CIN doit être au format: A123456 ou AB123456', regex='^[A-Z]{1,2}\\d{6}$')], verbose_name='CIN du chauffeur'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='numero_conteneur',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Le numéro de conteneur doit être au format: ABCD1234567', regex='^[A-Z]{4}\\d{7}$')], verbose_name='Numéro de conteneur'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='operation',
            field=models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=10, verbose_name="Type d'opération"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='plaque_camion',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='La plaque doit être au format: 123-A-456 ou 1234-ABC-12', regex='^\\d{3,4}-[A-Z]{1,3}-\\d{1,4}$')], verbose_name='Plaque du camion'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='sens_trafic',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Sens du trafic'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='type_conteneur',
            field=models.CharField(choices=[('plein', 'Plein'), ('vide', 'Vide')], max_length=5, verbose_name='Type de conteneur'),
        ),
    ]
